-- RUNNING QUERIES TO PERFORM VARIOUS ACTIONS--

-- Getting all orders by a Users (Users and Vendors)
--Customer query
SELECT * FROM Users;
SELECT o.OrderID , o.OrderDate , o.TotalAmount , u.FullName
FROM Orders o JOIN Users u
ON o.UserID = u.UserID WHERE o.UserId =2;

--Vendors query
SELECT * FROM Vendors;
SELECT o.OrderID , o.TotalAmount , o.VendorID , v.VendorName
FROM Orders o JOIN Vendors v
ON o.UserID = v.VendorID WHERE o.VendorID=1;

--Ordres summary with items (Orders , OrdersItem Product)
SELECT * FROM Orders;
SELECT * FROM OrderItems;
SELECT * FROM Products;
SELECT  o.OrderID , p.Name , oi.Quantity , oi.Price
FROM Orders o JOIN OrderItems oi 
ON o.OrderID = oi.OrderID
JOIN Products p
ON p.ProductID = oi.ProductID;

-- Total Revenue generated by each vendor
SELECT * FROM Vendors;
SELECT * FROM Orders;
SELECT v.VendorName ,SUM(o.TotalAmount) AS "TotalRevenue"
FROM Orders o JOIN Vendors v
ON o.VendorID = v.VendorID
GROUP BY v.VendorName
ORDER BY "TotalRevenue" DESC;

--Top  3 BEstSelling Produts--
SELECT * FROM Products;
SELECT * FROM OrderItems;
SELECT TOP 3 p.Name , SUM(oi.Quantity) AS "TotalSold"
FROM OrderItems oi JOIN Products p
ON P.ProductID = oi.ProductID
GROUP BY p.Name
ORDER BY TotalSold DESC;

-- AVERAG PRODUCT RATING
SELECT * FROM Reviews;
SELECT * FROM Products;
SELECT p.Name , AVG(r.Rating) AS AvgRatings
FROM  Reviews r JOIN Products p
ON p.ProductID = r.ProductID
GROUP BY p.Name;

-- dELIVERY STATUS OF PARTICULAR ORDER
SELECT * FROM DeliveryStatus;
SELECT * FROM Orders;
SELECT * FROM Status;
-- FOR ALL ORDERS
SELECT o.OrderID , s.StatusName , d.UpdatedAt
FROM  DeliveryStatus d JOIN Status s 
ON s.StatusID = d.DeliveryID
JOIN Orders o
ON o.OrderID = d.OrderID; 

--FOR INDIVIDUAL ORDERS
SELECT o.OrderID , s.StatusName , d.UpdatedAt
FROM  DeliveryStatus d JOIN Status s 
ON s.StatusID = d.DeliveryID
JOIN Orders o
ON o.OrderID = d.OrderID
WHERE o.OrderID = 4; 

-- Daily orders count--
SELECT * FROM OrderItems;
SELECT * FROM Orders;
SELECT * FROM Users;

SELECT OrderDate ,COUNT(*) AS TotalOrders
FROM Orders 
GROUP BY OrderDate;

INSERT INTO Orders VALUES (5 ,6 ,GETDATE(),500);

-- Top customer by ordr value
SELECT * FROM Users;
SELECT * FROM Orders;
SELECT u.FullName , SUM(o.TotalAmount) AS TotalSpent
FROM Orders o JOIN Users u 
ON u.UserID = o.UserID
GROUP BY FullName
ORDER BY Totalspent DESC;

-- LOW STOCK PRODUCCT PER VENDOR
SELECT * FROM Vendors;
SELECT * FROM Products;
SELECT * FROM Inventory;
SELECT v.VendorName , p.Name ,i.QuantityAvailable
FROM Inventory i JOIN Vendors v
ON i.VendorID = v.VendorID
JOIN Products p 
ON i.ProductID = p.ProductID
ORDER BY QuantityAvailable ASC;

-- SEARCH PRODUCT BY KEYWORD (FLEXIBLE QUERY)
SELECT * FROM Products;
SELECT * FROM Products 
WHERE Name LIKE '%Shirt%'; 